global.php

why?
=> global display of messages
how?
=> Add global page

integration global page

---

login.php

why ?
This allows them to retain our visitors, who can then participate more easily in the life of the site.
how ?
integrate page login

integrate login page

---

index.php
pages/examples/register.php
register.php

. why?
Registration of a member
.How
Save the member information in session

integrate register page

---

global.php
index.php

Why ?
Home page index
How ?
I created the index.php file

content home page default

---

login.php

why?
=> Update login page
how?
=> Add new register

update login page

---

inc/db_connect.php
inc/register_action.php.php
register.php

. why?
Connect to the database
. how?
Put it in include file

Add db connect

---

global.php
register.php

why?
=> update global and register pages
how?
=> add some fonctinnality

update global and register pages

---

global.php
inc/register_action.php.php

Why ?
The message list is still static
How ?
Create php code with connection to database to get dynamic message list

Dynamic message List

---

inc/register_action.php
register.php

. why?
action of the register
. how?
use a query of a request

register action

---

global.php
inc/register_action.php

. why?
correct the redirection
. how?
add index.php to the url

refactore register action

---

inc/login_action.php
index.php

why?
=> update index.php
how?
=> add session

refactore session save

---

inc/login_action.php
index.php

why?
=> update index.php
how?
=> valid session

clear index.php

---

inc/register_action.php

. why?
correct the redirection
. how?
put php in the place of html

correct redirect html to php

---

inc/db_connect.php
inc/login_action.php
login.php

why ?
loggin user 
how ?
check loggin with php

resolve login action and login redirect

---

global.php
inc/login_action.php
inc/register_action.php
login.php

clear code and resolve error

---

global.php
inc/login_action.php
inc/register_action.php
inc/sendmessage.php
inc/sql-send-message.php
index.php

resolve send message action

---

global.php
inc/login_action.php
inc/register_action.php
index.php

why?
=> username and id to session
How?
=> update register and register_action.php

resolve adding username and id to session

---

inc/db_connect.php
inc/login_action.php
inc/sql-send-message.php

why?
formatting the code
how?
remove them at the line and put the space

format code sql

---

global.php
index.php

why?
=> valid session
how?
=> update global and index pages

add session validation

---

inc/login_action.php
login.php

Why ?
If the username or password doesn't match, there is no error message
How ?
Show error message when username or password failed

Login failure error message

---

inc/login_action.php
inc/register_action.php

why ?
manage user
how ?
use sha1

Authentification

---

global.php
logout.php

why ?
to deconnect 
how ?
redirect to page login

create page deconnexion

---

bdd/hdb.sql
inc/login_action.php
inc/register_action.php

resolve conflict

---

bdd/hdb.sql

why?
conflict
how?
for someone who want to execut sql in here local

resolve database sql syntax

---

global.php
inc/sendmessage.php

resolve conflict3

---

global.php
inc/login_action.php
inc/sendmessage.php
login.php
register.php

Why?
Need required for input
How?
Show error message

resolve message error
